MODULE BOXM
    REAL, ALLOCATABLE, DIMENSION(:,:,:,:,:) :: RC, DJ, Y, YP, EM, FL
    REAL, ALLOCATABLE, DIMENSION(:,:,:) :: H2O, RO2, O2, P, L
    REAL, ALLOCATABLE, DIMENSION(:) :: M
    REAL :: DTS
    INTEGER :: TS
CONTAINS
    SUBROUTINE DERIV(TS)
    END SUBROUTINE DERIV
 
    SUBROUTINE CHEMCO(TS)
    END SUBROUTINE CHEMCO
    
    SUBROUTINE PHOTOL(TS)
    END SUBROUTINE PHOTOL

    SUBROUTINE CALC_AEROSOL(TS)
    END SUBROUTINE CALC_AEROSOL

END MODULE