MODULE BOXM
    REAL, ALLOCATABLE, DIMENSION(:,:,:,:) :: RC, DJ, Y, YP, EM
    REAL, ALLOCATABLE, DIMENSION(:,:,:) :: H2O, RO2, O2, P, L
    REAL, ALLOCATABLE, DIMENSION(:) :: M
    REAL :: DTS
    
    SUBROUTINE READ_NETCDF_DATA(file_path)

    SUBROUTINE DERIV(TS)
    END SUBROUTINE

    SUBROUTINE CHEMCO(TS)
    END SUBROUTINE
    
    SUBROUTINE PHOTOL(TS)
    END SUBROUTINE

    SUBROUTINE CALC_AEROSOL(TS)
    END SUBROUTINE

    SUBROUTINE WRITE_NETCDF_DATA(file_path)

END MODULE