# Run benchmark tests

name: Benchmark tests

on:
  # # run on tag push
  # push:
  #   tags: [ "*" ]

  # Allows run manually from the Actions tab
  workflow_dispatch:

# Global variables
env:
  PYCONTRAILS_CACHE_DIR: '${{ github.workspace }}/.cache/pycontrails'

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  benchmark-test:
    runs-on: ubuntu-latest

    # set from https://github.com/google-github-actions/auth
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    # https://github.com/easimon/maximize-build-space
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 4096
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: pyproject.toml

    - name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Install pycontrails (dev)
      run: make dev-install

    - name: Install pycontrails-bada extension
      run: |
        mkdir -p ~/.ssh/ && ssh-keyscan github.com > ~/.ssh/known_hosts
        gcloud secrets versions access latest --secret="contrails-301217-github-ssh-key" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        pip install "pycontrails-bada @ git+ssh://git@github.com/contrailcirrus/pycontrails-bada.git"

    # download data
    - name: BADA files
      working-directory: ./tests/benchmark/cocip/
      run: |
        mkdir -p bada
        gcloud storage cp -r gs://contrails-301217-bada/bada/bada3 bada/
        gcloud storage cp -r gs://contrails-301217-bada/bada/bada4 bada/

    - name: Download inputs & outputs
      working-directory: ./tests/benchmark/cocip/
      run: |
        make download-inputs
        make download-outputs

    - name: Show environment
      working-directory: ./tests/benchmark/cocip/
      run: |
        df -h
        du * -h
        pwd
        ls -lash
        which python
        python --version
        python -m pip list
        python -m pip check

    - name: Compare
      working-directory: ./tests/benchmark/cocip/
      run: make compare
