# Heavily copied from xarray
# https://github.com/pydata/xarray/blob/main/.github/workflows/testpypi-release.yaml

name: Build and upload pycontrails to Test PyPI

on:
  workflow_dispatch:

jobs:
  build-dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install build twine

    - name: Build a binary wheel and a source tarball
      run: python -m build

    - name: Check the distribution
      run: twine check --strict dist/*

    - name: Upload the distribution
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

  test-dist:
    needs: build-dist
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        pyversion: ['3.9', '3.10', '3.11']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.pyversion }}

    - name: Download the distribution
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: List the contents of the distribution
      run: ls -lh dist

    - name: Install the wheel
      run: |
        pip install --upgrade pip
        pip install dist/pycontrails*.whl
        python -c "import pycontrails; print(pycontrails.__version__)"

  publish-dist:
    needs: test-dist
    runs-on: ubuntu-latest

    steps:
    - name: Download the distribution
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: Publish distribution 📦 to Test PyPI
      uses: pypa/gh-action-pypi-publish@v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
        verbose: true
